### ISSUE TITLE
How does triggerTransform work with the new graphql-subscriptions API?

### ISSUE THREAD

**Issue by scf4** [davidyaha/graphql-redis-subscriptions#71] opened 2017-07-11 19:08 UTC
The readme still talks about the deprecated `subscriptionManager` etc.

**Comment by davidyaha** [comment] 2017-07-11 20:04
Duplicate of #67 
Feel free to open a PR if you can. If not, I'll try to get to it as soon as I can.
Thanks for the interest in this package!

**Closed** 2017-07-12 06:31 UTC
