### ISSUE TITLE
Message is not getting into websocket

### ISSUE THREAD

**Issue by kunjee17** [davidyaha/graphql-redis-subscriptions#186] opened 2019-10-17 12:22 UTC
We are having event emitter working in our project, and graphql with web socket is also working. We just replaced that with redis subscription. Message are getting published and subscribed perfectly from redis. But somehow it is not getting published into web socket. 

Seems little weird as there are no other error. 

It would be great if you can help me debug this.

**Comment by jarone** [comment] 2019-10-24 03:33
Check the code that posted the message, confirming that the first-level key in the published message data structure is consistent with the Subscriptions defined in the schema.

for example：

schema:

```graphql
type Message {
    content: String
}
type Subscription {
    postMessage: Message
}
```

resolver:

```javascript
...
pubsub.publish('channelNameOfRedis', { postMessage: { content: 'hi~' } })
...

**Comment by kunjee17** [comment] 2019-10-24 05:01
@jarone thanks for reply. I ll have a look at  it.

**Comment by davidyaha** [comment] 2019-11-14 12:18
Hey @kunjee17, have you resolved this issue?
If not, it would greatly help if you could provide a reproduction repo of the issue.

**Comment by kunjee17** [comment] 2019-11-15 11:08
@davidyaha not yet. I have to put thing on hold because of other issue in project. But will look into it again and will try to give repo for same. Thanks for following up.

**Comment by davidyaha** [comment] 2019-11-26 17:04
Okay @kunjee17. Closing for now, feel to re-open when you get back to it.

**Closed by davidyaha** 2019-11-26 17:04 UTC

**Comment by Dartv** [comment] 2020-01-13 12:40
Having the same issue. @kunjee17 did you solve this?

**Comment by davidyaha** [comment] 2020-01-13 13:06
Hey @Dartv!
As this problem can be caused by multiple reasons, could you provide a reproduction repository?
I might be able to help figure the problem out.

**Comment by kunjee17** [comment] 2020-01-14 20:26
@Dartv sorry couldn't got chance to get to that issue. It is still open issue for my project as well. But as soon as I get to issue will surely put it here. For us also it is kind required to get multiple instance of graphql server.
